// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: exp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumExpUpdateOperationMode int32

const (
	EnumExpUpdateOperationMode_OperationModeNone   EnumExpUpdateOperationMode = 0
	EnumExpUpdateOperationMode_OperationModeAdd    EnumExpUpdateOperationMode = 1
	EnumExpUpdateOperationMode_OperationModeSet    EnumExpUpdateOperationMode = 2
	EnumExpUpdateOperationMode_OperationModeRemove EnumExpUpdateOperationMode = 3
	EnumExpUpdateOperationMode_OperationModeDelete EnumExpUpdateOperationMode = 4
)

// Enum value maps for EnumExpUpdateOperationMode.
var (
	EnumExpUpdateOperationMode_name = map[int32]string{
		0: "OperationModeNone",
		1: "OperationModeAdd",
		2: "OperationModeSet",
		3: "OperationModeRemove",
		4: "OperationModeDelete",
	}
	EnumExpUpdateOperationMode_value = map[string]int32{
		"OperationModeNone":   0,
		"OperationModeAdd":    1,
		"OperationModeSet":    2,
		"OperationModeRemove": 3,
		"OperationModeDelete": 4,
	}
)

func (x EnumExpUpdateOperationMode) Enum() *EnumExpUpdateOperationMode {
	p := new(EnumExpUpdateOperationMode)
	*p = x
	return p
}

func (x EnumExpUpdateOperationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumExpUpdateOperationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_exp_proto_enumTypes[0].Descriptor()
}

func (EnumExpUpdateOperationMode) Type() protoreflect.EnumType {
	return &file_exp_proto_enumTypes[0]
}

func (x EnumExpUpdateOperationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumExpUpdateOperationMode.Descriptor instead.
func (EnumExpUpdateOperationMode) EnumDescriptor() ([]byte, []int) {
	return file_exp_proto_rawDescGZIP(), []int{0}
}

// setValueMode https://github.com/aws/aws-sdk-go-v2/blob/main/feature/dynamodb/expression/operand.go
// set value use special way
type EnumExpUpdateSetValMode int32

const (
	EnumExpUpdateSetValMode_SetValModeNone        EnumExpUpdateSetValMode = 0
	EnumExpUpdateSetValMode_SetValModePlus        EnumExpUpdateSetValMode = 1
	EnumExpUpdateSetValMode_SetValModeMinus       EnumExpUpdateSetValMode = 2
	EnumExpUpdateSetValMode_SetValModeListAppend  EnumExpUpdateSetValMode = 3
	EnumExpUpdateSetValMode_SetValModeIfNotExists EnumExpUpdateSetValMode = 4
)

// Enum value maps for EnumExpUpdateSetValMode.
var (
	EnumExpUpdateSetValMode_name = map[int32]string{
		0: "SetValModeNone",
		1: "SetValModePlus",
		2: "SetValModeMinus",
		3: "SetValModeListAppend",
		4: "SetValModeIfNotExists",
	}
	EnumExpUpdateSetValMode_value = map[string]int32{
		"SetValModeNone":        0,
		"SetValModePlus":        1,
		"SetValModeMinus":       2,
		"SetValModeListAppend":  3,
		"SetValModeIfNotExists": 4,
	}
)

func (x EnumExpUpdateSetValMode) Enum() *EnumExpUpdateSetValMode {
	p := new(EnumExpUpdateSetValMode)
	*p = x
	return p
}

func (x EnumExpUpdateSetValMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumExpUpdateSetValMode) Descriptor() protoreflect.EnumDescriptor {
	return file_exp_proto_enumTypes[1].Descriptor()
}

func (EnumExpUpdateSetValMode) Type() protoreflect.EnumType {
	return &file_exp_proto_enumTypes[1]
}

func (x EnumExpUpdateSetValMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumExpUpdateSetValMode.Descriptor instead.
func (EnumExpUpdateSetValMode) EnumDescriptor() ([]byte, []int) {
	return file_exp_proto_rawDescGZIP(), []int{1}
}

type ExpUpdateSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" dynamodbav:",omitempty"`
	SetValMode EnumExpUpdateSetValMode `protobuf:"varint,2,opt,name=SetValMode,proto3,enum=pb.EnumExpUpdateSetValMode" json:"SetValMode,omitempty" dynamodbav:",omitempty"`
}

func (x *ExpUpdateSet) Reset() {
	*x = ExpUpdateSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpUpdateSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpUpdateSet) ProtoMessage() {}

func (x *ExpUpdateSet) ProtoReflect() protoreflect.Message {
	mi := &file_exp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpUpdateSet.ProtoReflect.Descriptor instead.
func (*ExpUpdateSet) Descriptor() ([]byte, []int) {
	return file_exp_proto_rawDescGZIP(), []int{0}
}

func (x *ExpUpdateSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExpUpdateSet) GetSetValMode() EnumExpUpdateSetValMode {
	if x != nil {
		return x.SetValMode
	}
	return EnumExpUpdateSetValMode_SetValModeNone
}

type ExpUpdateItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationMode EnumExpUpdateOperationMode `protobuf:"varint,1,opt,name=OperationMode,proto3,enum=pb.EnumExpUpdateOperationMode" json:"OperationMode,omitempty" dynamodbav:",omitempty"`
	ExpUpdateSets []*ExpUpdateSet            `protobuf:"bytes,2,rep,name=ExpUpdateSets,proto3" json:"ExpUpdateSets,omitempty" dynamodbav:",omitempty"`
}

func (x *ExpUpdateItem) Reset() {
	*x = ExpUpdateItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpUpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpUpdateItem) ProtoMessage() {}

func (x *ExpUpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_exp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpUpdateItem.ProtoReflect.Descriptor instead.
func (*ExpUpdateItem) Descriptor() ([]byte, []int) {
	return file_exp_proto_rawDescGZIP(), []int{1}
}

func (x *ExpUpdateItem) GetOperationMode() EnumExpUpdateOperationMode {
	if x != nil {
		return x.OperationMode
	}
	return EnumExpUpdateOperationMode_OperationModeNone
}

func (x *ExpUpdateItem) GetExpUpdateSets() []*ExpUpdateSet {
	if x != nil {
		return x.ExpUpdateSets
	}
	return nil
}

var File_exp_proto protoreflect.FileDescriptor

var file_exp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x65, 0x78, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x5f, 0x0a, 0x0c, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x4d, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65,
	0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x44, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x45,
	0x6e, 0x75, 0x6d, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x36, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x74, 0x52, 0x0d, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x73,
	0x2a, 0x91, 0x01, 0x0a, 0x1a, 0x45, 0x6e, 0x75, 0x6d, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x15, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x74,
	0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x10, 0x04, 0x2a, 0x8b, 0x01, 0x0a, 0x17, 0x45, 0x6e, 0x75, 0x6d, 0x45, 0x78, 0x70,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x4d, 0x6f,
	0x64, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x10, 0x02, 0x12, 0x18, 0x0a,
	0x14, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x70, 0x70, 0x65, 0x6e, 0x64, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x56, 0x61,
	0x6c, 0x4d, 0x6f, 0x64, 0x65, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x10, 0x04, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_exp_proto_rawDescOnce sync.Once
	file_exp_proto_rawDescData = file_exp_proto_rawDesc
)

func file_exp_proto_rawDescGZIP() []byte {
	file_exp_proto_rawDescOnce.Do(func() {
		file_exp_proto_rawDescData = protoimpl.X.CompressGZIP(file_exp_proto_rawDescData)
	})
	return file_exp_proto_rawDescData
}

var file_exp_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_exp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_exp_proto_goTypes = []interface{}{
	(EnumExpUpdateOperationMode)(0), // 0: pb.EnumExpUpdateOperationMode
	(EnumExpUpdateSetValMode)(0),    // 1: pb.EnumExpUpdateSetValMode
	(*ExpUpdateSet)(nil),            // 2: pb.ExpUpdateSet
	(*ExpUpdateItem)(nil),           // 3: pb.ExpUpdateItem
}
var file_exp_proto_depIdxs = []int32{
	1, // 0: pb.ExpUpdateSet.SetValMode:type_name -> pb.EnumExpUpdateSetValMode
	0, // 1: pb.ExpUpdateItem.OperationMode:type_name -> pb.EnumExpUpdateOperationMode
	2, // 2: pb.ExpUpdateItem.ExpUpdateSets:type_name -> pb.ExpUpdateSet
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_exp_proto_init() }
func file_exp_proto_init() {
	if File_exp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpUpdateSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpUpdateItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exp_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exp_proto_goTypes,
		DependencyIndexes: file_exp_proto_depIdxs,
		EnumInfos:         file_exp_proto_enumTypes,
		MessageInfos:      file_exp_proto_msgTypes,
	}.Build()
	File_exp_proto = out.File
	file_exp_proto_rawDesc = nil
	file_exp_proto_goTypes = nil
	file_exp_proto_depIdxs = nil
}
