// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: activity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumRankT int32

const (
	EnumRankT_RankTNone EnumRankT = 0
	EnumRankT_RankTDay  EnumRankT = 1
	EnumRankT_RankTWeek EnumRankT = 2
)

// Enum value maps for EnumRankT.
var (
	EnumRankT_name = map[int32]string{
		0: "RankTNone",
		1: "RankTDay",
		2: "RankTWeek",
	}
	EnumRankT_value = map[string]int32{
		"RankTNone": 0,
		"RankTDay":  1,
		"RankTWeek": 2,
	}
)

func (x EnumRankT) Enum() *EnumRankT {
	p := new(EnumRankT)
	*p = x
	return p
}

func (x EnumRankT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumRankT) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_proto_enumTypes[0].Descriptor()
}

func (EnumRankT) Type() protoreflect.EnumType {
	return &file_activity_proto_enumTypes[0]
}

func (x EnumRankT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumRankT.Descriptor instead.
func (EnumRankT) EnumDescriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

type TableRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pk        string `protobuf:"bytes,1,opt,name=Pk,proto3" json:"Pk,omitempty" dynamodbav:",omitempty"`          //rank#<t>#<date>
	Sk        string `protobuf:"bytes,2,opt,name=Sk,proto3" json:"Sk,omitempty" dynamodbav:",omitempty"`          //user#<UserID>
	Gsi2Pk    string `protobuf:"bytes,3,opt,name=Gsi2Pk,proto3" json:"Gsi2Pk,omitempty" dynamodbav:",omitempty"`  //rank#<t>#<date>
	Gsi2Sk    int64  `protobuf:"varint,4,opt,name=Gsi2Sk,proto3" json:"Gsi2Sk,omitempty" dynamodbav:",omitempty"` //<ZeroPaddedScore>
	CreatedAt int32  `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty" dynamodbav:",omitempty"`
	Version   int64  `protobuf:"varint,6,opt,name=Version,proto3" json:"Version,omitempty" dynamodbav:",omitempty"`
}

func (x *TableRank) Reset() {
	*x = TableRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRank) ProtoMessage() {}

func (x *TableRank) ProtoReflect() protoreflect.Message {
	mi := &file_activity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRank.ProtoReflect.Descriptor instead.
func (*TableRank) Descriptor() ([]byte, []int) {
	return file_activity_proto_rawDescGZIP(), []int{0}
}

func (x *TableRank) GetPk() string {
	if x != nil {
		return x.Pk
	}
	return ""
}

func (x *TableRank) GetSk() string {
	if x != nil {
		return x.Sk
	}
	return ""
}

func (x *TableRank) GetGsi2Pk() string {
	if x != nil {
		return x.Gsi2Pk
	}
	return ""
}

func (x *TableRank) GetGsi2Sk() int64 {
	if x != nil {
		return x.Gsi2Sk
	}
	return 0
}

func (x *TableRank) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TableRank) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_activity_proto protoreflect.FileDescriptor

var file_activity_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x61,
	0x6e, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x50, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x50, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x53, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x73, 0x69, 0x32, 0x50, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x47, 0x73, 0x69, 0x32, 0x50, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x73,
	0x69, 0x32, 0x53, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x47, 0x73, 0x69, 0x32,
	0x53, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2a, 0x37, 0x0a, 0x09, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x61, 0x6e, 0x6b, 0x54,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x44,
	0x61, 0x79, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x61, 0x6e, 0x6b, 0x54, 0x57, 0x65, 0x65,
	0x6b, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_activity_proto_rawDescOnce sync.Once
	file_activity_proto_rawDescData = file_activity_proto_rawDesc
)

func file_activity_proto_rawDescGZIP() []byte {
	file_activity_proto_rawDescOnce.Do(func() {
		file_activity_proto_rawDescData = protoimpl.X.CompressGZIP(file_activity_proto_rawDescData)
	})
	return file_activity_proto_rawDescData
}

var file_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_activity_proto_goTypes = []interface{}{
	(EnumRankT)(0),    // 0: pb.EnumRankT
	(*TableRank)(nil), // 1: pb.TableRank
}
var file_activity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_activity_proto_init() }
func file_activity_proto_init() {
	if File_activity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activity_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_proto_goTypes,
		DependencyIndexes: file_activity_proto_depIdxs,
		EnumInfos:         file_activity_proto_enumTypes,
		MessageInfos:      file_activity_proto_msgTypes,
	}.Build()
	File_activity_proto = out.File
	file_activity_proto_rawDesc = nil
	file_activity_proto_goTypes = nil
	file_activity_proto_depIdxs = nil
}
